# Discord Config
app_id: "your app id"
bot_key: "your bot key"
bot_token: "your BOT TOKEN (CAREFUL CRITICAL INFO. DO NOT PUSH THIS TO REMOTE REPO)"
bot_permission: "bot permission code"
guild_id: "guild_id"

# SSH Config
ssh_port: 22
ssh_user: "your ssh user"
ssh_passwod: "your ssh user password"

# RCON Config
rcon_port: "your RCON port"
rcon_pwd: "your RCON password"
rcon_timeout: 10 # time in seconds

# General Config
server: "your IP or DDNS address"
start_file: "your server start script (e.g. start_server.sh)"
start_path: "your start script parent path"
update_script: "path to your steamcmd update script"
server_file: "path to you server initialization file (.ini)"